name: dart_mqtt
description: a mqtt library to easy connect via tcp/ssl,dependence xtransport,developing,not stable.
version: 1.0.4
repository: https://github.com/hkloudou/darts/tree/main/dart_mqtt
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  xtransport: ^0.0.5
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
